In [8]:
import pandas as pd
from sklearn import preprocessing
from scipy.io import arff

# Read the divorce data
divorce_df = pd.read_csv("divorce_data/divorce.csv")
divorce_df

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr46  \
0       2     2     4     1     0     0     0     0     0      0  ...      2   
1       4     4     4     4     4     0     0     4     4      4  ...      2   
2       2     2     2     2     1     3     2     1     1      2  ...      3   
3       3     2     3     2     3     3     3     3     3      3  ...      2   
4       2     2     1     1     1     1     0     0     0      0  ...      2   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
165     0     0     0     0     0     0     0     0     0      0  ...      1   
166     0     0     0     0     0     0     0     0     0      0  ...      4   
167     1     1     0     0     0     0     0     0     0      1  ...      3   
168     0     0     0     0     0     0     0     0     0      0  ...      3   
169     0     0     0     0     0     0     0     1     0      0  ...      3   

     Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  Class  
0        1      3      3      3      2      3      2      1      1  
1        2      3      4      4      4      4      2      2      1  
2        2      3      1      1      1      2      2      2      1  
3        2      3      3      3      3      2      2      2      1  
4        1      2      3      2      2      2      1      0      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
165      0      4      1      1      4      2      2      2      0  
166      1      2      2      2      2      3      2      2      0  
167      0      2      0      1      1      3      0      0      0  
168      3      2      2      3      2      4      3      1      0  
169      4      4      0      1      3      3      3      1      0  

[170 rows x 55 columns]

In [11]:
#Check for NULLs in the value
nullcount = divorce_df.isnull().sum().sort_values(ascending=False)
print(nullcount)

Class    0
Atr14    0
Atr25    0
Atr24    0
Atr23    0
Atr22    0
Atr21    0
Atr20    0
Atr19    0
Atr18    0
Atr17    0
Atr16    0
Atr15    0
Atr13    0
Atr27    0
Atr12    0
Atr11    0
Atr10    0
Atr9     0
Atr8     0
Atr7     0
Atr6     0
Atr5     0
Atr4     0
Atr3     0
Atr2     0
Atr26    0
Atr28    0
Atr54    0
Atr42    0
Atr53    0
Atr52    0
Atr51    0
Atr50    0
Atr49    0
Atr48    0
Atr47    0
Atr46    0
Atr45    0
Atr44    0
Atr43    0
Atr41    0
Atr29    0
Atr40    0
Atr39    0
Atr38    0
Atr37    0
Atr36    0
Atr35    0
Atr34    0
Atr33    0
Atr32    0
Atr31    0
Atr30    0
Atr1     0
dtype: int64


In [12]:
#Normalize the data
values = divorce_df.values #returns a numpy array
print(values)
min_max_scaler = preprocessing.MinMaxScaler()
values_scaled = min_max_scaler.fit_transform(values)
divorce_scaled_df = pd.DataFrame(values_scaled)
divorce_scaled_df

[[2 2 4 ... 2 1 1]
 [4 4 4 ... 2 2 1]
 [2 2 2 ... 2 2 1]
 ...
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 3 1 0]
 [0 0 0 ... 3 1 0]]


0     1     2     3     4     5     6     7     8     9   ...    45  \
0    0.50  0.50  1.00  0.25  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.50   
1    1.00  1.00  1.00  1.00  1.00  0.00  0.00  1.00  1.00  1.00  ...  0.50   
2    0.50  0.50  0.50  0.50  0.25  0.75  0.50  0.25  0.25  0.50  ...  0.75   
3    0.75  0.50  0.75  0.50  0.75  0.75  0.75  0.75  0.75  0.75  ...  0.50   
4    0.50  0.50  0.25  0.25  0.25  0.25  0.00  0.00  0.00  0.00  ...  0.50   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
165  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.25   
166  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  1.00   
167  0.25  0.25  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.25  ...  0.75   
168  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.75   
169  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.25  0.00  0.00  ...  0.75   

       46    47    48    49    50    51    52    53   54  
0    0.25  0.75  0.75  0.75  0.50  0.75  0.50  0.25  1.0  
1    0.50  0.75  1.00  1.00  1.00  1.00  0.50  0.50  1.0  
2    0.50  0.75  0.25  0.25  0.25  0.50  0.50  0.50  1.0  
3    0.50  0.75  0.75  0.75  0.75  0.50  0.50  0.50  1.0  
4    0.25  0.50  0.75  0.50  0.50  0.50  0.25  0.00  1.0  
..    ...   ...   ...   ...   ...   ...   ...   ...  ...  
165  0.00  1.00  0.25  0.25  1.00  0.50  0.50  0.50  0.0  
166  0.25  0.50  0.50  0.50  0.50  0.75  0.50  0.50  0.0  
167  0.00  0.50  0.00  0.25  0.25  0.75  0.00  0.00  0.0  
168  0.75  0.50  0.50  0.75  0.50  1.00  0.75  0.25  0.0  
169  1.00  1.00  0.00  0.25  0.75  0.75  0.75  0.25  0.0  

[170 rows x 55 columns]

In [13]:
#Linear Algebra
import numpy as np

#data processing
import pandas as pd

#data visualization
import matplotlib.pyplot as plt

#Algorithm


In [14]:
pg_df = pd.read_csv("/Users/priyankasenapati/Desktop/Classwork/Pewlett-Hackard-Analysis/Data/dept_manager.csv")
pg_df

dept_no  emp_no   from_date     to_date
0     d001  110022  1985-01-01  1991-10-01
1     d001  110039  1991-10-01  9999-01-01
2     d002  110085  1985-01-01  1989-12-17
3     d002  110114  1989-12-17  9999-01-01
4     d003  110183  1985-01-01  1992-03-21
5     d003  110228  1992-03-21  9999-01-01
6     d004  110303  1985-01-01  1988-09-09
7     d004  110344  1988-09-09  1992-08-02
8     d004  110386  1992-08-02  1996-08-30
9     d004  110420  1996-08-30  9999-01-01
10    d005  110511  1985-01-01  1992-04-25
11    d005  110567  1992-04-25  9999-01-01
12    d006  110725  1985-01-01  1989-05-06
13    d006  110765  1989-05-06  1991-09-12
14    d006  110800  1991-09-12  1994-06-28
15    d006  110854  1994-06-28  9999-01-01
16    d007  111035  1985-01-01  1991-03-07
17    d007  111133  1991-03-07  9999-01-01
18    d008  111400  1985-01-01  1991-04-08
19    d008  111534  1991-04-08  9999-01-01
20    d009  111692  1985-01-01  1988-10-17
21    d009  111784  1988-10-17  1992-09-08
22    d009  111877  1992-09-08  1996-01-03
23    d009  111939  1996-01-03  9999-01-01